//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UchebPRAOA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UchebPracsEntities1 : DbContext
    {

        private static UchebPracsEntities1 _context;

        public static UchebPracsEntities1 GetContext()
        {
            if (_context == null)
            {
                _context = new UchebPracsEntities1();
            }
            return _context;
        }

        public UchebPracsEntities1()
            : base("name=UchebPracsEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Request> Request { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TechType> TechType { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
